version: "3"
services:
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    env_file: 
       - .env
    environment:
      RAILS_ENV: development
    networks:
        social:
networks:
    social:
      external:
        name: social
